.Dd November 20, 2015
.Dt MESSAGED 1
.Os
.Sh NAME
.Nm messaged
.Nd handling XMPP message tags
.Sh SYNOPSIS
.Nm
.Op Fl i Ar FD
.Op Fl o Ar FD
.Fl j Ar JID
.Fl d Ar DIR
.Sh DESCRIPTION
The
.Nm
utility processes xmpp message tags from STDIN.
It has a filesystem based front end like
.Xr ii 1 .
Users should not start this programm directly.
.Xr sj 1
runs it after a successful login.
.Sh ENVIRONMENT
.Ev SJ_DIR
.Sh SEE ALSO
.Xr ii 1 ,
.Xr iqd 1 ,
.Xr sj 1
.Sh STANDARDS
XMPP CORE
.%R RFC 6120 ,
XMPP IM
.%R RFC 6121
.Sh AUTHORS
.An -nosplit
The
.Nm
program was written by
.An Jan Klemkow Aq Mt j.klemkow@wemelug.de .
