.Dd November 20, 2015
.Dt SJ 1
.Os
.Sh NAME
.Nm sj
.Nd XMPP client daemon
.Sh SYNOPSIS
tcpclient host port [tlsc] \\
.Nm
.Op Fl d Ar dir
.Op Fl r Ar resource
.Op Fl s Ar server
.Op Fl u Ar user
.Sh DESCRIPTION
The
.Nm
daemon is a client for the XMPP (Jabber) chat protocol. It handles the
protocol initiation, authentication and keep-alive pings.  During the
STARTTLS part of the initiation,
.Nm
automatically starts
.Xr tlsc 1
with its own arguments.
After an XMPP session is established
.Nm
starts
.Xr messaged 1 ,
.Xr presenced 1
and
.Xr iqd 1
and delegates all corresponding stanzas to these daemons via a
.Xr pipe 2 .
.Nm
exits if one of these pipes is widowed.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl d Ar dir
Path to sj directory stucture; defaults to current working directory.
.It Fl r Ar resource
Resource for this XMPP session.
.It Fl s Ar server
XMPP server domain name.
.It Fl u Ar user
XMPP username.
.El
.Sh ENVIRONMENT
Command line options, when provided, override the environment variables.
.Bl -tag -width SJ_PASSWORD
.It Ev SJ_DIR
See option 
.Fl d Ar dir
.It Ev SJ_RESOURCE
See option
.Fl r Ar resource
.It Ev SJ_SERVER
See option
.Fl s Ar server
.It Ev SJ_USER
See option
.Fl u Ar user
.El
.Sh EXAMPLES
For a Jabber ID of user@example.org:
.Bl -tag -width Ds
.It env SJ_USER=user SJ_SERVER=example.org tcpclient example.org 5222 sj
This is the recommended way to connect to the default (unencrypted) port and
start
.Xr tlsc 1
implicitly through
.Nm
itself after the STARTTLS handshake.
.It env SJ_USER=user SJ_SERVER=example.org tcpclient example.org 5223 tlsc sj
Using the encrypted port and explicity calling
.Xr tlsc .
This way
.Nm
does not do the STARTTLS handshake itself.
.El
.Sh SEE ALSO
.Xr ii 1 ,
.Xr iqd 1 ,
.Xr messaged 1 ,
.Xr presenced 1 ,
.Xr socks 1 ,
.Xr tlsc 1
.Sh STANDARDS
XMPP CORE
.%R RFC 6120 ,
XMPP IM
.%R RFC 6121 ,
.%R XEP-0199 XMPP Ping
.Sh AUTHORS
.An -nosplit
The
.Nm
program was written by
.An Jan Klemkow Aq Mt j.klemkow@wemelug.de .
